[project]
name = "ksp-krpc-rocket-avionics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "krpc>=0.5.4",
    "matplotlib>=3.9.3",
    "numpy>=2.1.3",
    "prometheus-client>=0.21.1",
    "psutil>=6.1.0",
    "scipy>=1.14.1",
]
