version: '3.8'
name: ksp-avionics
services:
  fsw:
    profiles:
      - fsw
    build:
      context: ../
      dockerfile: infra/Dockerfile
    container_name: fsw
#    ports:
#      - "8012:8012"
    network_mode: host
#    networks:
#      - telemetry_net
    # add internal gateway host to access host krpc server, see also https://stackoverflow.com/a/62431165
#    extra_hosts:
#      - host.docker.internal:host-gateway
    environment:
#      KRPC_ADDRESS: host.docker.internal
      TELEM_PUBLISH_RATE: 10 # hz
      PYTHONUNBUFFERED: 1
    command: "uv run minerva1.py"

  prometheus:
    profiles:
      - metrics_backend
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
#    ports:
#      - "9090:9090"
    network_mode: host
#    networks:
#      - telemetry_net

  grafana:
    profiles:
      - metrics_backend
    image: grafana/grafana-oss:latest
    container_name: grafana
#    ports:
#      - "3000:3000"
    network_mode: host
#    networks:
#      - telemetry_net
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # for simplicity, in real use set a stronger password
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:Z
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:Z
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:Z
      - ./grafana/dashboards:/var/lib/grafana/dashboards:Z
#      - ./grafana/data:/var/lib/grafana # so changes to dashboards survive a restart, requires ownership of the dir by user 472

#networks:
#  telemetry_net: