{
 "title": "DCX Avionics Overview",
 "tags": [
  "Overview",
  "DCX"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Altitude",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "surface_altitude", "legendFormat": "surface_altitude" },
    { "expr": "altitude", "legendFormat": "altitude" }
   ]
  },
  {
   "title": "Velocity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "velocity", "legendFormat": "velocity" },
    { "expr": "vertical_vel", "legendFormat": "vertical_vel" },
    { "expr": "horizontal_vel", "legendFormat": "horizontal_vel" }
   ]
  },
  {
   "title": "Landing Params",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "distance_to_pad", "legendFormat": "distance_to_pad" },
    { "expr": "current_horizontal_velocity", "legendFormat": "current_horizontal_velocity" }
   ]
  },
  {
   "title": "Throttle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "throttle", "legendFormat": "throttle" }
   ]
  },
  {
   "title": "GNC mode 2a",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "distance_pitch", "legendFormat": "distance_pitch" },
    { "expr": "velocity_pitch", "legendFormat": "velocity_pitch" },
    { "expr": "pitch_input", "legendFormat": "pitch_input" }
   ]
  },
  {
   "title": "GNC mode 2b",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pitch_input", "legendFormat": "pitch_input" },
    { "expr": "heading_error", "legendFormat": "heading_error" },
    { "expr": "roll", "legendFormat": "roll" },
    { "expr": "roll_input", "legendFormat": "roll_input" }
   ]
  },
  {
   "title": "GNC mode 3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pitch", "legendFormat": "pitch" }
   ]
  },
  {
   "title": "Control Mode",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 30, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "control_mode{} > 0", "legendFormat": "control_mode" }
   ]
  }
 ]
}