{
 "title": "Simulation host performance",
 "tags": [
  "Overview",
  "Host",
  "Performance"
 ],
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory (GiB)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes / 1000000000",
     "legendFormat": "process_virtual_memory_bytes"
    },
    {
     "expr": "process_resident_memory_bytes / 1000000000",
     "legendFormat": "process_resident_memory_bytes"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1s]) * 100",
     "legendFormat": "Avionics process CPU %"
    },
    { "expr": "system_cpu_percent", "legendFormat": "System CPU %" }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "process_open_fds" },
    { "expr": "process_max_fds", "legendFormat": "process_max_fds" }
   ]
  }
 ]
}